import type { EditorTemplate } from '../templates';

// Generated DS components (themed, token-based) — authored by the ds-components-author workflow.
export const designComponentsExtra: EditorTemplate[] = [
  {
    "id": "ds-agenda",
    "name": "DS · Agenda",
    "description": "Agenda con el Design System activo.",
    "html": "<div class='dsag'><div class='dsag__head'><span class='dsag__dot'></span><div class='dsag__title'>{{agenda.title}}</div></div><ul class='dsag__list'><li class='dsag__item'><span class='dsag__num'>1</span><span class='dsag__text'>{{agenda.i1}}</span></li><li class='dsag__item'><span class='dsag__num'>2</span><span class='dsag__text'>{{agenda.i2}}</span></li><li class='dsag__item'><span class='dsag__num'>3</span><span class='dsag__text'>{{agenda.i3}}</span></li><li class='dsag__item'><span class='dsag__num'>4</span><span class='dsag__text'>{{agenda.i4}}</span></li></ul></div>",
    "css": ".dsag{position:absolute;right:70px;top:120px;display:flex;flex-direction:column;width:420px;padding:26px 28px 30px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dsag-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.2,.8,.25,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsag__head{display:flex;align-items:center;gap:14px;padding-bottom:18px;margin-bottom:18px;border-bottom:1px solid var(--ds-border,rgba(168,85,247,.35))}.dsag__dot{flex:0 0 auto;width:14px;height:14px;border-radius:50%;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 16px var(--ds-glow,rgba(168,85,247,.55))}.dsag__title{font-size:30px;font-weight:800;letter-spacing:.02em;color:var(--ds-text,#fff);text-transform:uppercase}.dsag__list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:14px}.dsag__item{display:flex;align-items:center;gap:16px;padding:12px 16px;background:var(--ds-surface-2,rgba(255,255,255,.04));border:1px solid var(--ds-border,rgba(168,85,247,.22));border-radius:calc(var(--ds-radius,16px) - 6px)}.dsag__num{flex:0 0 auto;display:flex;align-items:center;justify-content:center;width:38px;height:38px;border-radius:10px;font-size:19px;font-weight:800;color:var(--ds-on-accent,#0b0b12);background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 4px 14px var(--ds-glow,rgba(168,85,247,.4))}.dsag__text{font-size:20px;font-weight:600;color:var(--ds-text,#fff);line-height:1.25}@keyframes dsag-in{from{opacity:0;transform:translateY(-12px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"agenda\":{\"title\":\"Agenda\",\"i1\":\"Introducción\",\"i2\":\"Demo en vivo\",\"i3\":\"Preguntas\",\"i4\":\"Cierre\"}}"
  },
  {
    "id": "ds-caster-bar",
    "name": "DS · Casters",
    "description": "Casters con el Design System activo.",
    "html": "<div class='dscast'><div class='dscast__plate dscast__plate--left'><div class='dscast__avatar'></div><div class='dscast__info'><div class='dscast__name'>{{caster1.name}}</div><div class='dscast__handle'>{{caster1.handle}}</div></div></div><div class='dscast__center'><span class='dscast__vs'>VS</span><span class='dscast__label'>{{series.label}}</span></div><div class='dscast__plate dscast__plate--right'><div class='dscast__info dscast__info--right'><div class='dscast__name'>{{caster2.name}}</div><div class='dscast__handle'>{{caster2.handle}}</div></div><div class='dscast__avatar dscast__avatar--alt'></div></div></div>",
    "css": ".dscast{position:absolute;left:60px;bottom:60px;display:flex;align-items:stretch;gap:0;font-family:var(--ds-font,system-ui,sans-serif);animation:dscast-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.2,.8,.2,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dscast__plate{display:flex;align-items:center;gap:16px;min-width:300px;padding:14px 22px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55))}.dscast__plate--left{border-radius:var(--ds-radius,16px) 0 0 var(--ds-radius,16px);border-right:none;justify-content:flex-start}.dscast__plate--right{border-radius:0 var(--ds-radius,16px) var(--ds-radius,16px) 0;border-left:none;justify-content:flex-end}.dscast__avatar{flex:0 0 auto;width:54px;height:54px;border-radius:50%;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 18px var(--ds-glow,rgba(168,85,247,.45));position:relative}.dscast__avatar::after{content:'\\1F3A4';position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:26px}.dscast__avatar--alt{background:var(--ds-grad,linear-gradient(135deg,#22d3ee,#a855f7))}.dscast__info{display:flex;flex-direction:column;justify-content:center;gap:3px}.dscast__info--right{align-items:flex-end;text-align:right}.dscast__name{font-size:28px;font-weight:800;line-height:1;color:var(--ds-text,#fff)}.dscast__handle{font-size:14px;font-weight:600;letter-spacing:.04em;color:var(--ds-accent,#22d3ee)}.dscast__center{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;padding:10px 26px;background:var(--ds-surface-2,rgba(30,32,48,.96));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-left:none;border-right:none;box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));z-index:1}.dscast__vs{font-size:22px;font-weight:900;line-height:1;letter-spacing:.06em;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;color:var(--ds-accent,#22d3ee)}.dscast__label{font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.16em;color:var(--ds-muted,rgba(255,255,255,.7));white-space:nowrap}@keyframes dscast-in{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"caster1\":{\"name\":\"Aurora\",\"handle\":\"@aurora\"},\"caster2\":{\"name\":\"Nexo\",\"handle\":\"@nexo\"},\"series\":{\"label\":\"GRAN FINAL\"}}"
  },
  {
    "id": "ds-countdown",
    "name": "DS · Cuenta Regresiva",
    "description": "Cuenta Regresiva con el Design System activo.",
    "html": "<div class='dscd'><div class='dscd__pill'><span class='dscd__clock' aria-hidden='true'></span><span class='dscd__label'>{{countdown.label}}</span><span class='dscd__time' data-countdown='300'>05:00</span></div></div>",
    "css": ".dscd{position:absolute;left:820px;top:90px;font-family:var(--ds-font,system-ui,sans-serif);animation:dscd-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.22,1,.36,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dscd__pill{display:inline-flex;align-items:center;gap:18px;padding:14px 26px 14px 18px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));backdrop-filter:blur(6px)}.dscd__clock{position:relative;flex:0 0 auto;width:38px;height:38px;border-radius:50%;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 18px var(--ds-glow,rgba(168,85,247,.45))}.dscd__clock::before,.dscd__clock::after{content:'';position:absolute;left:50%;top:50%;background:var(--ds-on-accent,#0b0b12);border-radius:2px;transform-origin:bottom center}.dscd__clock::before{width:2.5px;height:11px;transform:translate(-50%,-100%)}.dscd__clock::after{width:2.5px;height:8px;transform:translate(-50%,-100%) rotate(95deg)}.dscd__label{font-size:16px;font-weight:600;text-transform:uppercase;letter-spacing:.14em;color:var(--ds-muted,#9aa0b4);white-space:nowrap}.dscd__time{font-size:46px;font-weight:800;line-height:1;letter-spacing:.02em;font-variant-numeric:tabular-nums;color:var(--ds-text,#fff);text-shadow:0 0 22px var(--ds-glow,rgba(168,85,247,.45))}@keyframes dscd-in{from{opacity:0;transform:translateY(-14px) scale(.96)}to{opacity:1;transform:translateY(0) scale(1)}}",
    "variables": "{\"countdown\":{\"label\":\"Empezamos en\"}}"
  },
  {
    "id": "ds-episode-card",
    "name": "DS · Episodio (Podcast)",
    "description": "Episodio (Podcast) con el Design System activo.",
    "html": "<div class='dsep'><div class='dsep__glow'></div><div class='dsep__head'><span class='dsep__mic'>🎙️</span><span class='dsep__show'>{{show.name}}</span><span class='dsep__live'>PODCAST</span></div><div class='dsep__row'><span class='dsep__badge'><span class='dsep__badge-tag'>EP</span><span class='dsep__badge-num'>{{episode.number}}</span></span><div class='dsep__title'>{{episode.title}}</div></div><div class='dsep__wave'><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div></div>",
    "css": ".dsep{position:absolute;left:80px;bottom:96px;width:620px;box-sizing:border-box;padding:26px 30px 24px;display:flex;flex-direction:column;gap:18px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dsep-in var(--ds-dur-slow, .55s) var(--ds-ease-entrance, cubic-bezier(.2,.8,.2,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsep__glow{position:absolute;top:-120px;right:-120px;width:260px;height:260px;border-radius:50%;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));filter:blur(60px);opacity:.4;pointer-events:none}.dsep__head{position:relative;display:flex;align-items:center;gap:12px}.dsep__mic{font-size:22px;line-height:1}.dsep__show{font-size:20px;font-weight:800;letter-spacing:.04em;color:var(--ds-text,#fff)}.dsep__live{margin-left:auto;font-size:12px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:var(--ds-on-accent,#0b0b12);background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));padding:5px 12px;border-radius:999px;box-shadow:0 0 18px var(--ds-glow,rgba(168,85,247,.45))}.dsep__row{position:relative;display:flex;align-items:center;gap:18px}.dsep__badge{flex:none;display:flex;flex-direction:column;align-items:center;justify-content:center;min-width:84px;padding:12px 10px;background:var(--ds-surface-2,rgba(255,255,255,.06));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:calc(var(--ds-radius,16px) - 4px)}.dsep__badge-tag{font-size:13px;font-weight:800;letter-spacing:.22em;text-transform:uppercase;color:var(--ds-accent,#22d3ee)}.dsep__badge-num{font-size:44px;font-weight:900;line-height:1;color:var(--ds-text,#fff)}.dsep__title{font-size:30px;font-weight:800;line-height:1.18;color:var(--ds-text,#fff);text-shadow:0 2px 10px rgba(0,0,0,.45)}.dsep__wave{position:relative;display:flex;align-items:flex-end;gap:6px;height:22px}.dsep__wave span{flex:1;border-radius:999px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));animation:dsep-eq 1.1s ease-in-out infinite}.dsep__wave span:nth-child(1){height:40%;animation-delay:0s}.dsep__wave span:nth-child(2){height:90%;animation-delay:.15s}.dsep__wave span:nth-child(3){height:55%;animation-delay:.3s}.dsep__wave span:nth-child(4){height:100%;animation-delay:.45s}.dsep__wave span:nth-child(5){height:60%;animation-delay:.6s}.dsep__wave span:nth-child(6){height:85%;animation-delay:.75s}.dsep__wave span:nth-child(7){height:45%;animation-delay:.9s}@keyframes dsep-eq{0%,100%{transform:scaleY(.5)}50%{transform:scaleY(1)}}@keyframes dsep-in{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"show\":{\"name\":\"CodeTalks\"},\"episode\":{\"number\":\"42\",\"title\":\"El futuro de la IA\"}}"
  },
  {
    "id": "ds-goal-bar",
    "name": "DS · Meta",
    "description": "Meta con el Design System activo.",
    "html": "<div class='dsgoal'><div class='dsgoal__head'><span class='dsgoal__icon'>★</span><span class='dsgoal__label'>{{goal.label}}</span></div><div class='dsgoal__track'><div class='dsgoal__fill' style='width:{{goal.percent}}%'><span class='dsgoal__shine'></span></div></div><div class='dsgoal__foot'><span class='dsgoal__count'><span class='dsgoal__current'>{{goal.current}}</span><span class='dsgoal__sep'>/</span><span class='dsgoal__target'>{{goal.target}}</span></span><span class='dsgoal__pct'>{{goal.percent}}%</span></div></div>",
    "css": ".dsgoal{position:absolute;left:60px;bottom:60px;box-sizing:border-box;width:420px;padding:22px 26px 20px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);animation:dsgoal-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.2,.8,.25,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsgoal__head{display:flex;align-items:center;gap:10px;margin-bottom:14px}.dsgoal__icon{display:inline-flex;align-items:center;justify-content:center;width:30px;height:30px;border-radius:999px;font-size:16px;color:var(--ds-on-accent,#0b0b12);background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 16px var(--ds-glow,rgba(168,85,247,.45))}.dsgoal__label{font-size:18px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;color:var(--ds-text,#fff);text-shadow:0 2px 8px rgba(0,0,0,.55)}.dsgoal__track{position:relative;height:18px;border-radius:999px;background:var(--ds-surface-2,rgba(255,255,255,.08));border:1px solid var(--ds-border,rgba(168,85,247,.35));overflow:hidden}.dsgoal__fill{position:relative;height:100%;min-width:18px;border-radius:999px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 14px var(--ds-glow,rgba(168,85,247,.45));animation:dsgoal-grow .9s cubic-bezier(.2,.8,.25,1) both;overflow:hidden}.dsgoal__shine{position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,.35),transparent);transform:translateX(-100%);animation:dsgoal-shine 2.6s ease-in-out 1s infinite}.dsgoal__foot{display:flex;align-items:baseline;justify-content:space-between;margin-top:13px}.dsgoal__count{font-size:15px;font-weight:600;color:var(--ds-muted,rgba(255,255,255,.6))}.dsgoal__current{font-size:24px;font-weight:800;color:var(--ds-text,#fff)}.dsgoal__sep{margin:0 4px;color:var(--ds-muted,rgba(255,255,255,.6))}.dsgoal__target{color:var(--ds-muted,rgba(255,255,255,.6))}.dsgoal__pct{font-size:20px;font-weight:800;letter-spacing:.02em;color:var(--ds-accent,#22d3ee);text-shadow:0 0 12px var(--ds-glow,rgba(34,211,238,.4))}@keyframes dsgoal-in{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}@keyframes dsgoal-grow{from{opacity:.4;transform:scaleX(.35);transform-origin:left}to{opacity:1;transform:scaleX(1);transform-origin:left}}@keyframes dsgoal-shine{0%{transform:translateX(-100%)}55%,100%{transform:translateX(220%)}}",
    "variables": "{\"goal\":{\"label\":\"Meta de subs\",\"current\":\"72\",\"target\":\"100\",\"percent\":\"72\"}}"
  },
  {
    "id": "ds-host-guest",
    "name": "DS · Anfitrión / Invitado",
    "description": "Anfitrión / Invitado con el Design System activo.",
    "html": "<div class='dshg'><div class='dshg__plate dshg--host'><div class='dshg__accent'></div><div class='dshg__body'><div class='dshg__name'>{{host.name}}</div><div class='dshg__role'>{{host.role}}</div></div></div><div class='dshg__plate dshg--guest'><div class='dshg__dot'></div><div class='dshg__body'><div class='dshg__name'>{{guest.name}}</div><div class='dshg__role'>{{guest.role}}</div></div></div></div>",
    "css": ".dshg{position:absolute;left:80px;bottom:90px;display:flex;align-items:stretch;gap:18px;font-family:var(--ds-font,system-ui,sans-serif);animation:dshg-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.22,1,.36,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dshg__plate{position:relative;display:flex;align-items:stretch;min-width:300px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));overflow:hidden}.dshg__accent{width:8px;flex:none;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 22px var(--ds-glow,rgba(168,85,247,.55))}.dshg__body{padding:16px 26px;display:flex;flex-direction:column;justify-content:center;gap:5px}.dshg__name{font-size:32px;font-weight:800;line-height:1.05;color:var(--ds-text,#fff);text-shadow:0 1px 3px rgba(0,0,0,.55)}.dshg__role{font-size:14px;font-weight:700;text-transform:uppercase;letter-spacing:.14em;color:var(--ds-accent,#22d3ee)}.dshg--host .dshg__name{padding-top:1px}.dshg--host .dshg__role{color:var(--ds-accent,#a855f7)}.dshg--guest{background:var(--ds-surface,rgba(17,18,27,.92))}.dshg--guest .dshg__body{padding-left:24px}.dshg--guest .dshg__role{color:var(--ds-accent-2,#22d3ee)}.dshg__dot{width:12px;height:12px;flex:none;align-self:center;margin-left:20px;border-radius:999px;background:var(--ds-accent-2,#22d3ee);box-shadow:0 0 14px var(--ds-glow,rgba(34,211,238,.6))}@keyframes dshg-in{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"host\":{\"name\":\"Marta\",\"role\":\"Anfitriona\"},\"guest\":{\"name\":\"Dr. Lee\",\"role\":\"Invitado\"}}"
  },
  {
    "id": "ds-map-rounds",
    "name": "DS · Mapa / Rondas",
    "description": "Mapa / Rondas con el Design System activo.",
    "html": "<div class='dsmap'><div class='dsmap__head'><span class='dsmap__icon'></span><span class='dsmap__name'>{{map.name}}</span></div><div class='dsmap__rounds'><span class='dsmap__round'>{{map.round}}</span><span class='dsmap__sep'>/</span><span class='dsmap__total'>{{map.total}}</span></div><div class='dsmap__dots'><span class='dsmap__dot dsmap__dot--on'></span><span class='dsmap__dot dsmap__dot--on'></span><span class='dsmap__dot dsmap__dot--on'></span><span class='dsmap__dot dsmap__dot--on'></span><span class='dsmap__dot dsmap__dot--on'></span><span class='dsmap__dot dsmap__dot--on'></span><span class='dsmap__dot dsmap__dot--on'></span><span class='dsmap__dot'></span><span class='dsmap__dot'></span><span class='dsmap__dot'></span><span class='dsmap__dot'></span><span class='dsmap__dot'></span><span class='dsmap__dot'></span></div></div>",
    "css": ".dsmap{position:absolute;left:60px;top:300px;display:inline-flex;flex-direction:column;gap:14px;padding:18px 24px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dsmap-in var(--ds-dur-slow, .45s) var(--ds-ease-entrance, cubic-bezier(.22,1,.36,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsmap::before{content:'';position:absolute;left:0;top:0;bottom:0;width:6px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee))}.dsmap__head{display:flex;align-items:center;gap:12px}.dsmap__icon{position:relative;width:22px;height:22px;flex:0 0 auto;border-radius:6px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 16px var(--ds-glow,rgba(168,85,247,.55))}.dsmap__icon::after{content:'';position:absolute;left:50%;top:50%;width:7px;height:7px;margin:-3.5px 0 0 -3.5px;border-radius:50%;background:var(--ds-surface,rgba(17,18,27,.92))}.dsmap__name{font-size:26px;font-weight:800;letter-spacing:.01em;color:var(--ds-text,#fff);text-shadow:0 1px 2px rgba(0,0,0,.5)}.dsmap__rounds{display:flex;align-items:baseline;gap:6px;line-height:1}.dsmap__round{font-size:40px;font-weight:900;color:var(--ds-accent,#22d3ee)}.dsmap__sep{font-size:26px;font-weight:700;color:var(--ds-muted,rgba(255,255,255,.55))}.dsmap__total{font-size:30px;font-weight:800;color:var(--ds-text,#fff)}.dsmap__dots{display:flex;flex-wrap:wrap;gap:9px;max-width:300px}.dsmap__dot{width:14px;height:14px;border-radius:50%;background:var(--ds-surface-2,rgba(255,255,255,.08));border:1px solid var(--ds-border,rgba(168,85,247,.35));box-sizing:border-box}.dsmap__dot--on{background:var(--ds-accent,#22d3ee);border-color:var(--ds-accent,#22d3ee);box-shadow:0 0 10px var(--ds-glow,rgba(34,211,238,.6))}@keyframes dsmap-in{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"map\":{\"name\":\"Ascent\",\"round\":\"7\",\"total\":\"13\"}}"
  },
  {
    "id": "ds-match-score",
    "name": "DS · Marcador (Esports)",
    "description": "Marcador (Esports) con el Design System activo.",
    "html": "<div class=\"dsmatch\"><div class=\"dsmatch__stage\">{{series.stage}}</div><div class=\"dsmatch__row\"><div class=\"dsmatch__team dsmatch__team--home\"><span class=\"dsmatch__name\">{{home.name}}</span><span class=\"dsmatch__score\" data-motion-pop=\"home.score\">{{home.score}}</span></div><div class=\"dsmatch__vs\">VS</div><div class=\"dsmatch__team dsmatch__team--away\"><span class=\"dsmatch__score\" data-motion-pop=\"away.score\">{{away.score}}</span><span class=\"dsmatch__name\">{{away.name}}</span></div></div></div>",
    "css": ".dsmatch{position:absolute;left:610px;top:46px;display:flex;flex-direction:column;align-items:stretch;width:700px;padding:18px 26px 22px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dsmatch-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.16,1,.3,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsmatch::before{content:'';position:absolute;left:0;top:0;right:0;height:4px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee))}.dsmatch__stage{align-self:center;margin-bottom:16px;padding:6px 18px;background:var(--ds-surface-2,rgba(255,255,255,.06));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:999px;font-size:15px;font-weight:700;text-transform:uppercase;letter-spacing:.18em;color:var(--ds-accent,#22d3ee);white-space:nowrap}.dsmatch__row{display:flex;align-items:center;justify-content:center;gap:20px}.dsmatch__team{flex:1;display:flex;align-items:center;gap:18px;min-width:0}.dsmatch__team--home{justify-content:flex-end;text-align:right}.dsmatch__team--away{justify-content:flex-start;text-align:left}.dsmatch__name{font-size:30px;font-weight:800;color:var(--ds-text,#fff);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-shadow:0 2px 8px rgba(0,0,0,.5)}.dsmatch__score{flex:0 0 auto;display:flex;align-items:center;justify-content:center;width:64px;height:64px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));border-radius:var(--ds-radius,16px);box-shadow:0 0 24px var(--ds-glow,rgba(168,85,247,.45));font-size:38px;font-weight:900;color:var(--ds-on-accent,#0b0b12)}.dsmatch__vs{flex:0 0 auto;font-size:18px;font-weight:800;letter-spacing:.1em;color:var(--ds-muted,rgba(255,255,255,.55))}@keyframes dsmatch-in{from{opacity:0;transform:translateY(-14px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"home\":{\"name\":\"Dragones\",\"score\":\"2\"},\"away\":{\"name\":\"Lobos\",\"score\":\"1\"},\"series\":{\"stage\":\"Semifinal · BO3\"}}"
  },
  {
    "id": "ds-meeting-bar",
    "name": "DS · Barra de Reunión",
    "description": "Barra de Reunión con el Design System activo.",
    "html": "<div class='dsmeet'><div class='dsmeet__dot'></div><div class='dsmeet__title'>{{meeting.title}}</div><div class='dsmeet__sep'></div><div class='dsmeet__clock'><span class='dsmeet__clock-ico'>◷</span><span class='dsmeet__time' data-clock='true'>00:00:00</span></div><div class='dsmeet__sep'></div><div class='dsmeet__people'><span class='dsmeet__people-ico'>👥</span><span class='dsmeet__people-text'>{{meeting.participants}}</span></div></div>",
    "css": ".dsmeet{position:absolute;left:560px;top:40px;display:flex;align-items:center;gap:20px;height:60px;padding:0 26px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);color:var(--ds-text,#fff);backdrop-filter:blur(8px);animation:dsmeet-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.22,1,.36,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsmeet__dot{width:12px;height:12px;border-radius:50%;flex:0 0 auto;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 0 4px var(--ds-glow,rgba(168,85,247,.25));animation:dsmeet-pulse 2s ease-in-out infinite}.dsmeet__title{font-size:22px;font-weight:800;letter-spacing:.01em;color:var(--ds-text,#fff);white-space:nowrap;max-width:360px;overflow:hidden;text-overflow:ellipsis}.dsmeet__sep{width:1px;height:28px;flex:0 0 auto;background:var(--ds-border,rgba(168,85,247,.35));opacity:.8}.dsmeet__clock{display:flex;align-items:center;gap:10px;padding:6px 14px;border-radius:calc(var(--ds-radius,16px) - 6px);background:var(--ds-surface-2,rgba(255,255,255,.06))}.dsmeet__clock-ico{font-size:16px;line-height:1;color:var(--ds-accent,#22d3ee)}.dsmeet__time{font-size:22px;font-weight:700;font-variant-numeric:tabular-nums;letter-spacing:.06em;color:var(--ds-accent,#22d3ee);min-width:106px;text-align:center}.dsmeet__people{display:flex;align-items:center;gap:10px;white-space:nowrap}.dsmeet__people-ico{font-size:16px;line-height:1;color:var(--ds-accent-2,#a855f7)}.dsmeet__people-text{font-size:16px;font-weight:600;letter-spacing:.02em;color:var(--ds-muted,rgba(255,255,255,.7))}@keyframes dsmeet-in{from{opacity:0;transform:translateY(-12px)}to{opacity:1;transform:translateY(0)}}@keyframes dsmeet-pulse{0%,100%{box-shadow:0 0 0 4px var(--ds-glow,rgba(168,85,247,.25))}50%{box-shadow:0 0 0 7px var(--ds-glow,rgba(168,85,247,.12))}}",
    "variables": "{\"meeting\":{\"title\":\"Sprint Review\",\"participants\":\"8 participantes\"}}"
  },
  {
    "id": "ds-mute-status",
    "name": "DS · Micrófono",
    "description": "Micrófono con el Design System activo.",
    "html": "<div class=\"dsmic\"><div class=\"dsmic__icon\">🎙</div><div class=\"dsmic__body\"><span class=\"dsmic__name\">{{mic.name}}</span><span class=\"dsmic__status\">{{mic.status}}</span></div></div>",
    "css": ".dsmic{position:absolute;left:70px;bottom:70px;display:inline-flex;align-items:center;gap:14px;padding:12px 22px 12px 14px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);animation:dsmic-in var(--ds-dur-slow, .45s) var(--ds-ease-entrance, cubic-bezier(.22,1,.36,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsmic__icon{display:flex;align-items:center;justify-content:center;width:46px;height:46px;flex:none;font-size:24px;line-height:1;border-radius:calc(var(--ds-radius,16px) - 4px);background:var(--ds-surface-2,rgba(255,255,255,.06));border:1px solid var(--ds-border,rgba(168,85,247,.35));box-shadow:0 0 18px var(--ds-glow,rgba(168,85,247,.35))}.dsmic__body{display:flex;flex-direction:column;justify-content:center;gap:3px}.dsmic__name{font-size:22px;font-weight:800;line-height:1.05;color:var(--ds-text,#fff)}.dsmic__status{font-size:13px;font-weight:700;line-height:1;text-transform:uppercase;letter-spacing:.14em;color:var(--ds-accent,#22d3ee)}@keyframes dsmic-in{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"mic\":{\"name\":\"Tú\",\"status\":\"Silenciado\"}}"
  },
  {
    "id": "ds-poll",
    "name": "DS · Encuesta",
    "description": "Encuesta con el Design System activo.",
    "html": "<div class='dspoll'><div class='dspoll__head'><span class='dspoll__icon'>★</span><span class='dspoll__q'>{{poll.question}}</span></div><div class='dspoll__rows'><div class='dspoll__row'><div class='dspoll__line'><span class='dspoll__opt'>{{poll.o1}}</span><span class='dspoll__pct'>{{poll.p1}}%</span></div><div class='dspoll__track'><span class='dspoll__bar' style='width:{{poll.p1}}%'></span></div></div><div class='dspoll__row'><div class='dspoll__line'><span class='dspoll__opt'>{{poll.o2}}</span><span class='dspoll__pct'>{{poll.p2}}%</span></div><div class='dspoll__track'><span class='dspoll__bar' style='width:{{poll.p2}}%'></span></div></div><div class='dspoll__row'><div class='dspoll__line'><span class='dspoll__opt'>{{poll.o3}}</span><span class='dspoll__pct'>{{poll.p3}}%</span></div><div class='dspoll__track'><span class='dspoll__bar' style='width:{{poll.p3}}%'></span></div></div></div></div>",
    "css": ".dspoll{position:absolute;right:70px;bottom:90px;width:440px;box-sizing:border-box;padding:24px 26px 26px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dspoll-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.22,1,.36,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dspoll__head{display:flex;align-items:center;gap:12px;margin-bottom:20px;padding-bottom:16px;border-bottom:1px solid var(--ds-border,rgba(168,85,247,.25))}.dspoll__icon{flex:0 0 auto;width:30px;height:30px;display:flex;align-items:center;justify-content:center;font-size:16px;border-radius:50%;color:var(--ds-on-accent,#0b0b12);background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 14px var(--ds-glow,rgba(168,85,247,.5))}.dspoll__q{font-size:22px;font-weight:800;line-height:1.2;color:var(--ds-text,#fff);text-shadow:0 1px 2px rgba(0,0,0,.4)}.dspoll__rows{display:flex;flex-direction:column;gap:16px}.dspoll__row{display:flex;flex-direction:column;gap:8px}.dspoll__line{display:flex;align-items:baseline;justify-content:space-between;gap:12px}.dspoll__opt{font-size:16px;font-weight:600;color:var(--ds-text,#fff)}.dspoll__pct{font-size:15px;font-weight:800;color:var(--ds-accent,#22d3ee)}.dspoll__track{position:relative;height:12px;border-radius:999px;background:var(--ds-surface-2,rgba(255,255,255,.08));overflow:hidden}.dspoll__bar{display:block;height:100%;border-radius:999px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));box-shadow:0 0 10px var(--ds-glow,rgba(168,85,247,.45));animation:dspoll-grow .8s cubic-bezier(.22,1,.36,1) both}@keyframes dspoll-in{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}@keyframes dspoll-grow{from{transform:scaleX(0);transform-origin:left}to{transform:scaleX(1);transform-origin:left}}",
    "variables": "{\"poll\":{\"question\":\"¿Qué tema sigue?\",\"o1\":\"Rendimiento\",\"p1\":\"58\",\"o2\":\"Seguridad\",\"p2\":\"27\",\"o3\":\"Diseño\",\"p3\":\"15\"}}"
  },
  {
    "id": "ds-prize-pool",
    "name": "DS · Premio",
    "description": "Premio con el Design System activo.",
    "html": "<div class='dsprz'><div class='dsprz__glow'></div><div class='dsprz__inner'><div class='dsprz__head'><span class='dsprz__dot'></span><span class='dsprz__label'>{{prize.label}}</span><span class='dsprz__dot'></span></div><div class='dsprz__amount'>{{prize.amount}}</div></div></div>",
    "css": ".dsprz{position:absolute;left:700px;top:60px;display:inline-flex;min-width:420px;padding:6px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dsprz-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.2,.8,.2,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsprz__glow{position:absolute;inset:-40%;background:radial-gradient(60% 60% at 50% 0%,var(--ds-glow,rgba(168,85,247,.35)),transparent 70%);pointer-events:none}.dsprz__inner{position:relative;flex:1;display:flex;flex-direction:column;align-items:center;gap:10px;padding:22px 40px;background:var(--ds-surface-2,rgba(255,255,255,.04));border-radius:calc(var(--ds-radius,16px) - 6px)}.dsprz__head{display:flex;align-items:center;gap:14px}.dsprz__dot{width:8px;height:8px;border-radius:50%;background:var(--ds-accent,#22d3ee);box-shadow:0 0 12px var(--ds-glow,rgba(168,85,247,.5))}.dsprz__label{font-size:18px;font-weight:700;text-transform:uppercase;letter-spacing:.32em;color:var(--ds-muted,#9aa3b2)}.dsprz__amount{font-size:92px;line-height:1;font-weight:900;letter-spacing:-.02em;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;color:var(--ds-accent,#22d3ee);filter:drop-shadow(0 6px 18px var(--ds-glow,rgba(168,85,247,.45)))}@keyframes dsprz-in{from{opacity:0;transform:translateY(-18px) scale(.96)}to{opacity:1;transform:translateY(0) scale(1)}}",
    "variables": "{\"prize\":{\"label\":\"PRIZE POOL\",\"amount\":\"$25,000\"}}"
  },
  {
    "id": "ds-recording",
    "name": "DS · REC + Ecualizador",
    "description": "REC + Ecualizador con el Design System activo.",
    "html": "<div class='dsrec'><span class='dsrec__dot'></span><span class='dsrec__label'>{{rec.label}}</span><span class='dsrec__eq'><i class='dsrec__bar'></i><i class='dsrec__bar'></i><i class='dsrec__bar'></i><i class='dsrec__bar'></i><i class='dsrec__bar'></i></span></div>",
    "css": ".dsrec{position:absolute;left:70px;top:70px;display:inline-flex;align-items:center;gap:14px;padding:12px 22px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);animation:dsrec-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.2,.8,.2,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsrec__dot{width:14px;height:14px;border-radius:50%;background:#ff3b3b;box-shadow:0 0 0 0 rgba(255,59,59,.7),0 0 12px 2px rgba(255,59,59,.55);animation:dsrec-pulse 1.4s ease-in-out infinite}.dsrec__label{font-size:22px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:var(--ds-text,#fff)}.dsrec__eq{display:inline-flex;align-items:flex-end;gap:4px;height:26px;padding-left:6px;margin-left:2px;border-left:1px solid var(--ds-border,rgba(168,85,247,.35))}.dsrec__bar{display:block;width:5px;height:30%;border-radius:3px;background:var(--ds-accent,#22d3ee);box-shadow:0 0 8px var(--ds-glow,rgba(34,211,238,.45));transform-origin:bottom;animation:dsrec-eq 1s ease-in-out infinite}.dsrec__bar:nth-child(1){animation-duration:.9s;animation-delay:-.2s}.dsrec__bar:nth-child(2){animation-duration:.7s;animation-delay:-.5s}.dsrec__bar:nth-child(3){animation-duration:1.1s;animation-delay:0s}.dsrec__bar:nth-child(4){animation-duration:.8s;animation-delay:-.35s}.dsrec__bar:nth-child(5){animation-duration:1s;animation-delay:-.65s}@keyframes dsrec-eq{0%,100%{height:25%}25%{height:90%}50%{height:45%}75%{height:100%}}@keyframes dsrec-pulse{0%,100%{box-shadow:0 0 0 0 rgba(255,59,59,.7),0 0 12px 2px rgba(255,59,59,.55);transform:scale(1)}50%{box-shadow:0 0 0 7px rgba(255,59,59,0),0 0 14px 3px rgba(255,59,59,.7);transform:scale(1.12)}}@keyframes dsrec-in{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"rec\":{\"label\":\"GRABANDO\"}}"
  },
  {
    "id": "ds-speaker-card",
    "name": "DS · Ponente (Webinar)",
    "description": "Ponente (Webinar) con el Design System activo.",
    "html": "<div class=\"dsspk\"><div class=\"dsspk__accent\"></div><div class=\"dsspk__body\"><div class=\"dsspk__eyebrow\"><span class=\"dsspk__dot\"></span><span class=\"dsspk__live\">EN VIVO</span></div><div class=\"dsspk__name\">{{speaker.name}}</div><div class=\"dsspk__meta\"><span class=\"dsspk__title\">{{speaker.title}}</span><span class=\"dsspk__sep\"></span><span class=\"dsspk__company\">{{speaker.company}}</span></div></div></div>",
    "css": ".dsspk{position:absolute;left:80px;bottom:96px;display:flex;align-items:stretch;min-width:420px;max-width:680px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55)),0 0 0 1px var(--ds-glow,rgba(168,85,247,.08));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dsspk-in var(--ds-dur-slow, .55s) var(--ds-ease-entrance, cubic-bezier(.22,.61,.36,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsspk__accent{flex:0 0 auto;width:10px;background:var(--ds-grad,linear-gradient(160deg,#a855f7,#22d3ee))}.dsspk__body{padding:18px 30px 20px 26px;display:flex;flex-direction:column;gap:8px;min-width:0}.dsspk__eyebrow{display:flex;align-items:center;gap:8px}.dsspk__dot{width:9px;height:9px;border-radius:50%;background:var(--ds-accent-2,#22d3ee);box-shadow:0 0 0 4px var(--ds-glow,rgba(34,211,238,.18));animation:dsspk-pulse 1.8s ease-in-out infinite}.dsspk__live{font-size:12px;font-weight:800;letter-spacing:.2em;text-transform:uppercase;color:var(--ds-accent-2,#22d3ee)}.dsspk__name{font-size:38px;line-height:1.05;font-weight:800;letter-spacing:-.01em;color:var(--ds-text,#fff);text-shadow:0 2px 8px rgba(0,0,0,.45);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dsspk__meta{display:flex;align-items:center;gap:12px;font-size:17px;font-weight:600}.dsspk__title{color:var(--ds-accent,#a855f7);text-transform:uppercase;letter-spacing:.08em;font-size:15px}.dsspk__sep{flex:0 0 auto;width:5px;height:5px;border-radius:50%;background:var(--ds-muted,rgba(255,255,255,.45))}.dsspk__company{color:var(--ds-muted,rgba(255,255,255,.7));font-weight:700;letter-spacing:.02em}@keyframes dsspk-in{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}@keyframes dsspk-pulse{0%,100%{opacity:1}50%{opacity:.45}}",
    "variables": "{\"speaker\":{\"name\":\"Elena Ruiz\",\"title\":\"Staff Engineer\",\"company\":\"Acme\"}}"
  },
  {
    "id": "ds-standings",
    "name": "DS · Clasificación (tabla)",
    "description": "Clasificación (tabla) con el Design System activo.",
    "html": "<div class='dsstd'><div class='dsstd__head'><span class='dsstd__icon'>☰</span><span class='dsstd__title'>{{head.title}}</span></div><div class='dsstd__list'><div class='dsstd__row dsstd__row--1'><span class='dsstd__rank'>1</span><span class='dsstd__name'>{{t1.name}}</span><span class='dsstd__pts'>{{t1.pts}}</span></div><div class='dsstd__row dsstd__row--2'><span class='dsstd__rank'>2</span><span class='dsstd__name'>{{t2.name}}</span><span class='dsstd__pts'>{{t2.pts}}</span></div><div class='dsstd__row dsstd__row--3'><span class='dsstd__rank'>3</span><span class='dsstd__name'>{{t3.name}}</span><span class='dsstd__pts'>{{t3.pts}}</span></div><div class='dsstd__row dsstd__row--4'><span class='dsstd__rank'>4</span><span class='dsstd__name'>{{t4.name}}</span><span class='dsstd__pts'>{{t4.pts}}</span></div></div></div>",
    "css": ".dsstd{position:absolute;left:60px;top:80px;width:440px;padding:0;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dsstd-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.22,1,.36,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dsstd__head{display:flex;align-items:center;gap:14px;padding:18px 24px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));border-bottom:1px solid var(--ds-border,rgba(168,85,247,.35))}.dsstd__icon{display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;font-size:18px;border-radius:10px;background:var(--ds-surface-2,rgba(255,255,255,.16));color:var(--ds-on-accent,#0b0b14)}.dsstd__title{font-size:24px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;color:var(--ds-on-accent,#0b0b14);text-shadow:0 1px 2px rgba(0,0,0,.25)}.dsstd__list{padding:10px 14px 16px}.dsstd__row{display:grid;grid-template-columns:46px 1fr auto;align-items:center;gap:14px;padding:12px 14px;margin-top:8px;background:var(--ds-surface-2,rgba(255,255,255,.05));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:calc(var(--ds-radius,16px) - 6px)}.dsstd__rank{display:inline-flex;align-items:center;justify-content:center;width:38px;height:38px;font-size:18px;font-weight:800;border-radius:50%;color:var(--ds-muted,rgba(255,255,255,.7));background:var(--ds-surface,rgba(17,18,27,.92));border:2px solid var(--ds-border,rgba(168,85,247,.35))}.dsstd__name{font-size:22px;font-weight:700;color:var(--ds-text,#fff);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dsstd__pts{font-size:22px;font-weight:800;color:var(--ds-accent,#22d3ee);font-variant-numeric:tabular-nums;min-width:38px;text-align:right}.dsstd__row--1{border-color:var(--ds-accent,#22d3ee)}.dsstd__row--1 .dsstd__rank{color:var(--ds-on-accent,#0b0b14);background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));border-color:transparent;box-shadow:0 0 18px var(--ds-glow,rgba(168,85,247,.5))}.dsstd__row--2 .dsstd__rank{color:var(--ds-text,#fff);border-color:var(--ds-accent-2,#a855f7)}@keyframes dsstd-in{from{opacity:0;transform:translateY(-14px)}to{opacity:1;transform:translateY(0)}}",
    "variables": "{\"head\":{\"title\":\"Clasificación\"},\"t1\":{\"name\":\"Dragones\",\"pts\":\"9\"},\"t2\":{\"name\":\"Lobos\",\"pts\":\"7\"},\"t3\":{\"name\":\"Titanes\",\"pts\":\"4\"},\"t4\":{\"name\":\"Furia\",\"pts\":\"3\"}}"
  },
  {
    "id": "ds-starting-soon",
    "name": "DS · Empezamos Pronto",
    "description": "Empezamos Pronto con el Design System activo.",
    "html": "<div class='dssoon'><div class='dssoon__glow'></div><div class='dssoon__panel'><div class='dssoon__dots'><span class='dssoon__dot'></span><span class='dssoon__dot'></span><span class='dssoon__dot'></span></div><div class='dssoon__title'>{{screen.title}}</div><div class='dssoon__rule'></div><div class='dssoon__subtitle'>{{screen.subtitle}}</div></div></div>",
    "css": ".dssoon{position:absolute;left:0;top:0;width:1920px;height:1080px;display:flex;align-items:center;justify-content:center;overflow:hidden;font-family:var(--ds-font,system-ui,sans-serif);background:radial-gradient(circle at 50% 42%,var(--ds-glow,rgba(168,85,247,.22)),transparent 60%),var(--ds-surface,rgba(17,18,27,.92))}.dssoon__glow{position:absolute;left:50%;top:42%;width:1100px;height:1100px;margin-left:-550px;margin-top:-550px;border-radius:50%;background:radial-gradient(circle,var(--ds-glow,rgba(168,85,247,.22)),transparent 62%);filter:blur(8px);animation:dssoonpulse 5.5s ease-in-out infinite}.dssoon__panel{position:relative;z-index:1;text-align:center;padding:72px 96px;background:var(--ds-surface-2,rgba(24,26,38,.72));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));animation:dssoonin var(--ds-dur-slow, .8s) var(--ds-ease-entrance, cubic-bezier(.16,1,.3,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dssoon__dots{display:flex;gap:14px;justify-content:center;margin-bottom:34px}.dssoon__dot{width:14px;height:14px;border-radius:50%;background:var(--ds-accent,#22d3ee);box-shadow:0 0 16px var(--ds-glow,rgba(34,211,238,.55));animation:dssoonbounce 1.4s ease-in-out infinite}.dssoon__dot:nth-child(2){background:var(--ds-accent-2,#a855f7);animation-delay:.18s}.dssoon__dot:nth-child(3){animation-delay:.36s}.dssoon__title{font-size:128px;line-height:1.02;font-weight:900;letter-spacing:.04em;text-transform:uppercase;color:var(--ds-text,#fff);background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;text-shadow:0 6px 40px var(--ds-glow,rgba(168,85,247,.35))}.dssoon__rule{width:200px;height:5px;margin:38px auto 30px;border-radius:999px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee))}.dssoon__subtitle{font-size:34px;font-weight:600;letter-spacing:.18em;text-transform:uppercase;color:var(--ds-muted,rgba(255,255,255,.72))}@keyframes dssoonin{from{opacity:0;transform:scale(.96)}to{opacity:1;transform:scale(1)}}@keyframes dssoonpulse{0%,100%{opacity:.6}50%{opacity:1}}@keyframes dssoonbounce{0%,100%{transform:translateY(0);opacity:.65}50%{transform:translateY(-12px);opacity:1}}",
    "variables": "{\"screen\":{\"title\":\"EMPEZAMOS PRONTO\",\"subtitle\":\"El directo comienza en breve\"}}"
  },
  {
    "id": "ds-ticker",
    "name": "DS · Ticker",
    "description": "Ticker con el Design System activo.",
    "html": "<div class='dstick'><div class='dstick__chip'><span class='dstick__dot'></span><span class='dstick__label'>{{ticker.label}}</span></div><div class='dstick__message'>{{ticker.message}}</div></div>",
    "css": ".dstick{position:absolute;left:60px;bottom:40px;display:flex;align-items:stretch;max-width:1100px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dstick-in var(--ds-dur-slow, .45s) var(--ds-ease-entrance, cubic-bezier(.2,.8,.2,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dstick__chip{display:flex;align-items:center;gap:10px;padding:0 22px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee));color:var(--ds-on-accent,#0b0b12);flex:0 0 auto}.dstick__dot{width:10px;height:10px;border-radius:50%;background:var(--ds-on-accent,#0b0b12);box-shadow:0 0 0 4px var(--ds-glow,rgba(168,85,247,.45));animation:dstick-pulse 1.6s ease-in-out infinite}.dstick__label{font-size:18px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;white-space:nowrap}.dstick__message{display:flex;align-items:center;padding:14px 30px;font-size:26px;font-weight:600;line-height:1.2;color:var(--ds-text,#fff);background:var(--ds-surface-2,rgba(255,255,255,.04));white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dstick__message::before{content:'\\2022';margin-right:14px;font-size:22px;color:var(--ds-accent,#22d3ee)}@keyframes dstick-in{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}@keyframes dstick-pulse{0%,100%{box-shadow:0 0 0 4px var(--ds-glow,rgba(168,85,247,.45))}50%{box-shadow:0 0 0 7px var(--ds-glow,rgba(168,85,247,.18))}}",
    "variables": "{\"ticker\":{\"label\":\"NOTICIAS\",\"message\":\"Bienvenidos al directo — sigue para no perderte nada\"}}"
  },
  {
    "id": "ds-topic-card",
    "name": "DS · Tarjeta de Segmento",
    "description": "Tarjeta de Segmento con el Design System activo.",
    "html": "<div class='dstopic'><div class='dstopic__bar'></div><div class='dstopic__body'><div class='dstopic__label'><span class='dstopic__dot'></span>{{segment.label}}</div><div class='dstopic__title'>{{segment.title}}</div></div></div>",
    "css": ".dstopic{position:absolute;left:560px;top:70px;display:flex;align-items:stretch;max-width:760px;min-width:420px;background:var(--ds-surface,rgba(17,18,27,.92));border:1px solid var(--ds-border,rgba(168,85,247,.35));border-radius:var(--ds-radius,16px);box-shadow:var(--ds-shadow,0 12px 36px rgba(0,0,0,.55));font-family:var(--ds-font,system-ui,sans-serif);overflow:hidden;animation:dstopic-in var(--ds-dur-slow, .5s) var(--ds-ease-entrance, cubic-bezier(.2,.8,.2,1)) both;animation-delay:calc(var(--ds-stagger,0ms) * var(--dsm-i,0))}.dstopic__bar{flex:0 0 auto;width:8px;background:var(--ds-grad,linear-gradient(135deg,#a855f7,#22d3ee))}.dstopic__body{padding:18px 30px 20px;min-width:0}.dstopic__label{display:inline-flex;align-items:center;gap:8px;font-size:15px;font-weight:800;text-transform:uppercase;letter-spacing:.18em;color:var(--ds-accent,#22d3ee);margin-bottom:8px}.dstopic__dot{width:9px;height:9px;border-radius:50%;background:var(--ds-accent,#22d3ee);box-shadow:0 0 12px var(--ds-glow,rgba(34,211,238,.7));animation:dstopic-pulse 1.8s ease-in-out infinite}.dstopic__title{font-size:38px;line-height:1.12;font-weight:800;color:var(--ds-text,#fff);text-shadow:0 2px 10px rgba(0,0,0,.45)}@keyframes dstopic-in{from{opacity:0;transform:translateY(-14px)}to{opacity:1;transform:translateY(0)}}@keyframes dstopic-pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.5;transform:scale(.78)}}",
    "variables": "{\"segment\":{\"label\":\"AHORA\",\"title\":\"Charlando con la comunidad\"}}"
  }
];
